/**
 * Mock data for testing the frontend when the API isn't available yet.
 * This can be used for development and testing purposes.
 */

export const mockDeck = {
  id: 'deck_001',
  name: 'Roland\'s Investigator Deck',
  investigator_name: 'Roland Banks',
  cards: [
    {
      code: '01001',
      name: '.45 Automatic',
      real_name: '.45 Automatic',
      cost: 4,
      type_name: 'Asset',
      class_name: 'Guardian',
      quantity: 2,
      traits: 'Item. Weapon. Firearm.',
      text: 'Uses (4 ammo). Spend 1 ammo: Fight. You get +1 combat and deal +1 damage for this attack.',
      pack_name: 'Core Set',
    },
    {
      code: '01006',
      name: 'Magnifying Glass',
      real_name: 'Magnifying Glass',
      cost: 1,
      type_name: 'Asset',
      class_name: 'Seeker',
      quantity: 2,
      traits: 'Item. Tool.',
      text: 'You get +1 intellect while investigating.',
      pack_name: 'Core Set',
    },
    {
      code: '01016',
      name: 'Machete',
      real_name: 'Machete',
      cost: 3,
      type_name: 'Asset',
      class_name: 'Guardian',
      quantity: 2,
      traits: 'Item. Weapon. Melee.',
      text: 'Fight. You deal +1 damage for this attack.',
      pack_name: 'Core Set',
    },
    {
      code: '01019',
      name: 'Guard Dog',
      real_name: 'Guard Dog',
      cost: 3,
      type_name: 'Asset',
      class_name: 'Guardian',
      quantity: 1,
      traits: 'Ally. Creature.',
      text: 'You get +1 combat. Forced - When you are dealt any amount of damage: Deal that amount of damage to Guard Dog.',
      pack_name: 'Core Set',
    },
    {
      code: '01020',
      name: 'Beat Cop',
      real_name: 'Beat Cop',
      cost: 4,
      type_name: 'Asset',
      class_name: 'Guardian',
      quantity: 2,
      traits: 'Ally. Police.',
      text: 'You get +1 combat. Discard Beat Cop: Fight. You get +2 combat and deal +1 damage for this attack.',
      pack_name: 'Core Set',
    },
    {
      code: '01031',
      name: 'Drawn to the Flame',
      real_name: 'Drawn to the Flame',
      cost: 0,
      type_name: 'Event',
      class_name: 'Seeker',
      quantity: 2,
      traits: 'Insight.',
      text: 'Discover 2 clues at your location. Place 1 doom on the current agenda.',
      pack_name: 'Core Set',
    },
    {
      code: '01089',
      name: 'Vicious Blow',
      real_name: 'Vicious Blow',
      cost: null,
      type_name: 'Skill',
      class_name: 'Guardian',
      quantity: 2,
      traits: 'Practiced.',
      text: 'If this attack defeats an enemy, deal 1 additional damage to it.',
      pack_name: 'Core Set',
    },
    {
      code: '01093',
      name: 'Shrivelling',
      real_name: 'Shrivelling',
      cost: 3,
      type_name: 'Asset',
      class_name: 'Mystic',
      quantity: 1,
      traits: 'Spell.',
      text: 'Uses (4 charges). Spend 1 charge: Fight. You get +2 combat and deal +1 damage for this attack.',
      pack_name: 'Core Set',
    },
  ],
};

export const mockCards = [
  {
    code: '01001',
    name: '.45 Automatic',
    real_name: '.45 Automatic',
    cost: 4,
    type_name: 'Asset',
    class_name: 'Guardian',
    traits: 'Item. Weapon. Firearm.',
    text: 'Uses (4 ammo). Spend 1 ammo: Fight. You get +1 combat and deal +1 damage for this attack.',
    pack_name: 'Core Set',
    position: 1,
    skill_willpower: 0,
    skill_intellect: 0,
    skill_combat: 1,
    skill_agility: 0,
  },
  {
    code: '01006',
    name: 'Magnifying Glass',
    real_name: 'Magnifying Glass',
    cost: 1,
    type_name: 'Asset',
    class_name: 'Seeker',
    traits: 'Item. Tool.',
    text: 'You get +1 intellect while investigating.',
    pack_name: 'Core Set',
    position: 6,
    skill_willpower: 0,
    skill_intellect: 1,
    skill_combat: 0,
    skill_agility: 0,
  },
  {
    code: '01016',
    name: 'Machete',
    real_name: 'Machete',
    cost: 3,
    type_name: 'Asset',
    class_name: 'Guardian',
    traits: 'Item. Weapon. Melee.',
    text: 'Fight. You deal +1 damage for this attack.',
    pack_name: 'Core Set',
    position: 16,
    skill_willpower: 0,
    skill_intellect: 0,
    skill_combat: 1,
    skill_agility: 0,
  },
  {
    code: '01019',
    name: 'Guard Dog',
    real_name: 'Guard Dog',
    cost: 3,
    type_name: 'Asset',
    class_name: 'Guardian',
    traits: 'Ally. Creature.',
    text: 'You get +1 combat. Forced - When you are dealt any amount of damage: Deal that amount of damage to Guard Dog.',
    pack_name: 'Core Set',
    position: 19,
    skill_willpower: 0,
    skill_intellect: 0,
    skill_combat: 1,
    skill_agility: 0,
  },
  {
    code: '01020',
    name: 'Beat Cop',
    real_name: 'Beat Cop',
    cost: 4,
    type_name: 'Asset',
    class_name: 'Guardian',
    traits: 'Ally. Police.',
    text: 'You get +1 combat. Discard Beat Cop: Fight. You get +2 combat and deal +1 damage for this attack.',
    pack_name: 'Core Set',
    position: 20,
    skill_willpower: 0,
    skill_intellect: 0,
    skill_combat: 1,
    skill_agility: 0,
  },
  {
    code: '01031',
    name: 'Drawn to the Flame',
    real_name: 'Drawn to the Flame',
    cost: 0,
    type_name: 'Event',
    class_name: 'Seeker',
    traits: 'Insight.',
    text: 'Discover 2 clues at your location. Place 1 doom on the current agenda.',
    pack_name: 'Core Set',
    position: 31,
    skill_willpower: 1,
    skill_intellect: 1,
    skill_combat: 0,
    skill_agility: 0,
  },
  {
    code: '01089',
    name: 'Vicious Blow',
    real_name: 'Vicious Blow',
    cost: null,
    type_name: 'Skill',
    class_name: 'Guardian',
    traits: 'Practiced.',
    text: 'If this attack defeats an enemy, deal 1 additional damage to it.',
    pack_name: 'Core Set',
    position: 89,
    skill_willpower: 0,
    skill_intellect: 0,
    skill_combat: 2,
    skill_agility: 0,
  },
  {
    code: '01093',
    name: 'Shrivelling',
    real_name: 'Shrivelling',
    cost: 3,
    type_name: 'Asset',
    class_name: 'Mystic',
    traits: 'Spell.',
    text: 'Uses (4 charges). Spend 1 charge: Fight. You get +2 combat and deal +1 damage for this attack.',
    pack_name: 'Core Set',
    position: 93,
    skill_willpower: 0,
    skill_intellect: 0,
    skill_combat: 2,
    skill_agility: 1,
  },
];

export const mockSimulation = {
  iterations: 1000,
  avg_turns_to_setup: 3.2,
  success_rate: 0.78,
  key_card_reliability: {
    '.45 Automatic': 0.85,
    'Magnifying Glass': 0.92,
    'Machete': 0.71,
    'Guard Dog': 0.58,
    'Beat Cop': 0.67,
  },
  draw_curves: {
    '.45 Automatic': 2.1,
    'Magnifying Glass': 1.8,
    'Machete': 3.5,
    'Guard Dog': 4.2,
    'Beat Cop': 3.8,
  },
  metrics: {
    avg_opening_hand_cost: 2.8,
    avg_resources_turn_5: 4.2,
    card_draw_efficiency: 0.88,
  },
};

